server:
  port: 8080  # This means your backend will run on http://localhost:8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/contact_manager?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: appuser   # or root if you haven't created appuser
    password: root

  jpa:
    hibernate:
      ddl-auto: update  # Automatically creates/updates tables based on entities
    show-sql: true       # Logs SQL queries in the terminal

jwt:
  secret: replace_this_with_a_long_random_secret
  expirationMs: 86400000  # 24 hours
  jwt:
    secret: 6zZxAEq7TKBEPNqCIHkTLHONqo86/yP9/IT4u7m/ZczS8yttDM+VZqc/OY2Qj5kR
    expirationMs: 86400000

